### ISSUE TITLE
Visible Native Horizontal Scrollbar in IE & Firefox

### ISSUE THREAD

**Issue by mfwonghk** [gromo/jquery.scrollbar#51] opened 2015-07-24 07:13 UTC
I have a sidebar with 100% height and a item menu inside.

http://jsfiddle.net/mfwonghk/ku9cmv56/

In 0.2.6 the native horizontal scrollbar is hidden. After updating to 0.2.8 it is visible in IE & Firefox.

Is this a bug or I need to change my CSS?

**Comment by gromo** [comment] 2015-07-24 07:23
There are small changes in CSS - in `.scroll-wrapper > .scroll-content {` properties `height` and `max-height` were changed

```
.scroll-wrapper > .scroll-content {
    border: none !important;
    box-sizing: content-box !important;
    height: auto;
    left: 0;
    margin: 0;
    max-height: none;
    max-width: none !important;
    overflow: scroll !important;
    padding: 0;
    position: relative !important;
    top: 0;
    width: auto !important;
}
```

**Comment by mfwonghk** [comment] 2015-07-24 07:33
Thank you for your quick response!

I am already using the 2.0.8 CSS. I tried replaceing "height: 100%;" with "max-height: 100%" in my "menu" class.

http://jsfiddle.net/s5ng001z/1/

No horizontal scrollbar in IE & Firefox now, but the "max-height" of ".scroll-content" won't update after resizing.

**Comment by gromo** [comment] 2015-07-24 07:53
Looks like I fixed one issue, but broke different part. I will research on it and fix in next few days. And you can roll back to previous version until I fix it

**Comment by gromo** [comment] 2015-07-24 10:57
I have updated your example with fixed version + I have updated CSS for your sidebar menu a little: http://jsfiddle.net/s5ng001z/4/

**Comment by mfwonghk** [comment] 2015-07-27 02:09
Thanks! It's working now.

**Closed** 2015-07-27 06:04 UTC
Labels: bug

**Comment by JustDoItSascha** [comment] 2015-08-13 06:24
Could you tell me, what the solution was? Because I have the same error!

**Comment by gromo** [comment] 2015-08-13 06:37
@JustDoItSascha 

Everything should work now in version 0.2.8, current git version is in development and unstable, please download stable one via download link. If you use stable version, prepare example on jsFiddle.net and I will try to help you.

**Comment by JustDoItSascha** [comment] 2015-08-13 08:54
@gromo Thanks for your fast reply. I used version 0.2.8, downloaded via bower. Now I use 0.2.6, downloaded manually (unfortunately it was not loadable via bower), and now it works. I can't fiddle it before tomorrow, but at the moment, with 0.2.6 it works.

It also just appeared on Firefox + Internet Explorer and ONLY on windows. Firefox on Mac worked like a charm.

The issue itself was that .scroll-content element got a margin-right: -17px. So it was wider than the scroll-wrapper and the scroll-wrapper had overflow: scroll... But the margin-right: -17px appeared only on FF and IE under Windows.

**Comment by gromo** [comment] 2015-08-13 09:31
@JustDoItSascha 

It's expected behavior and it works that way - adding negative margin to hide always visible scrollbars. Your problem hides somewhere else :)

**Comment by JustDoItSascha** [comment] 2015-08-13 09:41
But why is the margin-right: -17px only in FF and IE under windows? You are hiding the default scrollbars?

But nevertheless, if the wrapper is 250px width (like in my case) and the content has width: 100% and you add margin-right: -17px, the bounding box is 267 px. So if you set overflow to scroll, you will always see a scrollbar on the bottom, won't you?

But I see right now, maybe this is the failure: My sidebar doesn't have a fixed height.

**Comment by gromo** [comment] 2015-08-13 11:57
no need in fixed height. Can you prepare simple example on jsFiddle.net?

**Comment by JustDoItSascha** [comment] 2015-08-13 12:52
Yes, but not before tomorrow. :)
